name: Pip package

on:
  push:
    branches:
      - "*"
    # tags:
    #   - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Build
        run: |
          pip install -r requirements.txt

      - name: Test
        run: |
          python test.py
